/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.43
 * Generated at: 2022-12-28 04:58:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class pract_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Marvel Characters</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/introduce_characters.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/common.css\">\r\n");
      out.write("    <!-- 애니메이트 -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../library/animate/animate.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/swiper/swiper-bundle.min.css\"/>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- 헤더창 -->\r\n");
      out.write("    <header class=\"header\">\r\n");
      out.write("        <div class=\"header_nav\">\r\n");
      out.write("            <h1>\r\n");
      out.write("                <a href=\"../index.html\">\r\n");
      out.write("                    <img src=\"../img/Marvel_Logo.png\"  alt=\"logo\">\r\n");
      out.write("                </a>\r\n");
      out.write("            </h1>\r\n");
      out.write("            <!-- 모바일 로그인 -->\r\n");
      out.write("            <div class=\"menu_Mlogin\">\r\n");
      out.write("                  <a href=\"./login.html\">SIGN IN | JOIN</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- 메뉴박스 -->\r\n");
      out.write("            <div class=\"menu\">\r\n");
      out.write("                <nav>\r\n");
      out.write("                    <ul class=\"menu_main\">\r\n");
      out.write("                        <li class=\"main_list\">\r\n");
      out.write("                            <a>UNIVERSE</a>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <ul class=\"list_drop animate_animated animate_fadeIn\">\r\n");
      out.write("                                    <li><a href=\"./worldview.html\">WORLDVIEW</a></li>\r\n");
      out.write("                                    <li><a>CINEMATIC</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"main_list\">\r\n");
      out.write("                            <a href=\"./introduce_characters.html\">CHARACTERS</a>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <ul class=\"list_drop animate_animated animate_fadeIn\">\r\n");
      out.write("                                    <li><a href=\"./introduce_characters.html\">ALL CHARACTERS</a></li>\r\n");
      out.write("                                    <li><a href=\"./introduce_characters.html\">TEAMS & GROUPS</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"main_list\">\r\n");
      out.write("                            <a href=\"./news.html\">NEWS</a>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <ul class=\"list_drop animate_animated animate_fadeIn\">\r\n");
      out.write("                                    <li><a href=\"./news.html\">NEWS</a></li>\r\n");
      out.write("                                    <li><a href=\"./goods.html\">STORE</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"main_list\">\r\n");
      out.write("                            <a href=\"./marvel_movieClip.html\">MOVIES</a>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <ul class=\"list_drop animate_animated animate_fadeIn\">\r\n");
      out.write("                                    <li><a href=\"./UpcomingFilms.html\">RELEASE</a></li>\r\n");
      out.write("                                    <li><a href=\"./marvel_movieClip.html\">MOVIE CLIP</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- 로그인박스 -->\r\n");
      out.write("            <div class=\"menu_login\">\r\n");
      out.write("                    <a href=\"./login.html\">SIGN IN | JOIN</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"header_panel\"></div>\r\n");
      out.write("    </header>\r\n");
      out.write("        \r\n");
      out.write("    \r\n");
      out.write("    <main class=\"wrap\">\r\n");
      out.write("    <!-- 프로모션 컨텐츠 -->\r\n");
      out.write("            <section>\r\n");
      out.write("                <div class=\"promo_content\">\r\n");
      out.write("                    <a class=\"promo_content_btn\">REWARD YOUR MARVEL FANDOM WITH INSIDER</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </section>\r\n");
      out.write("            <!-- 첫화면 -->\r\n");
      out.write("            <section>\r\n");
      out.write("                <div class=\"background_photo\">\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <img src=\"../img/backgroundimage.png\"    alt=\"background_image\" >\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"background_write\">\r\n");
      out.write("                        <h1 id=\"background_write_h1\">MARVEL CHARACTERS</h1>\r\n");
      out.write("                        <h2 id=\"background_write_h2\">Get hooked on a hearty helping of heroes and villains from the humble House of Ideas!</h2>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </section>\r\n");
      out.write("            <!-- 광고 -->\r\n");
      out.write("            <section class=\"advertise\">\r\n");
      out.write("                <div class=\"advertis_box\">\r\n");
      out.write("                    <a href=\"https://www.marvel.com/unlimited?cid=dsp_housead_20210909_unlimited_launchads\">\r\n");
      out.write("                    <img src=\"https://tpc.googlesyndication.com/simgad/13295404199721664793\" alt=\"광고\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </section>\r\n");
      out.write("            <!-- 캐릭터 사진  -->\r\n");
      out.write("            <section class=\"introduce_characters\">\r\n");
      out.write("                <div class=\"featured_characters_title\">\r\n");
      out.write("                    <h1>CHARACTERS</h1>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!--  영역 만들기 -->\r\n");
      out.write("                <div class=\"featured_characters_image\">\r\n");
      out.write("                    <div class=\"border\">\r\n");
      out.write("                        <div class=\"featured_characters_movie_title\">\r\n");
      out.write("                            <h2>Doctor Strange in the Multiverse of Madness</h2>\r\n");
      out.write("                        </div>                \r\n");
      out.write("                    </div>\r\n");
      out.write("                    <ul class=\"featured_characters_sixhero\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"\"><img src=\"../img/characters1.png\"   alt=\"doctor_strange\"></a>\r\n");
      out.write("                            <div class=\"info\">\r\n");
      out.write("                                <h3>DOCTOR STRANGE</h3>\r\n");
      out.write("                                <P>STEPHEN STRANGE</P>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"\"><img src=\"../img/characters2.png\"  alt=\"wanda\"></a>\r\n");
      out.write("                            <div class=\"info\">\r\n");
      out.write("                                <h3>WANDA MAXIMOFF</h3>\r\n");
      out.write("                                <P></P>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"\"><img src=\"../img/characters3.png\"  alt=\"wang\"></a>\r\n");
      out.write("                            <div class=\"info\">\r\n");
      out.write("                                <h3>WONG</h3>\r\n");
      out.write("                                <P>SORCERER SUPREME</P>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"\"><img src=\"../img/characters4.png\"  alt=\"americachavez\"></a>\r\n");
      out.write("                            <div class=\"info\">\r\n");
      out.write("                                <h3>AMERICA CHAVEZ</h3>\r\n");
      out.write("                                <P></P>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"\"><img src=\"../img/characters5.png\"  alt=\"baronmordo\"></a>\r\n");
      out.write("                            <div class=\"info\">\r\n");
      out.write("                                <h3>BARON MORDO</h3>\r\n");
      out.write("                                <P></P>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"\"><img src=\"../img/characters6.png\"   alt=\"christinepalmer\"></a>                \r\n");
      out.write("                            <div class=\"info\">\r\n");
      out.write("                                <h3>CHRISTINE PALMER</h3>\r\n");
      out.write("                                <P></P>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <div class=\"border\">\r\n");
      out.write("                        <div class=\"featured_characters_movie_title\">\r\n");
      out.write("                            <h2>AVENGERS:ENDGAME</h2>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <ul class=\"featured_characters_sixhero\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"\"><img src=\"../img/characters7.png\"   alt=\"captainamerica\"></a>\r\n");
      out.write("                            <div class=\"info\">\r\n");
      out.write("                                    <h3>CAPTAIN AMERICA</h3>\r\n");
      out.write("                                    <P>STEVE ROGERS</P>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"\"><img src=\"../img/characters8.png\"  alt=\"thanos\"></a>\r\n");
      out.write("                            <div class=\"info\">\r\n");
      out.write("                                <h3>THANOS</h3>\r\n");
      out.write("                                <P></P>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"\"><img src=\"../img/characters9.png\"  alt=\"ironman2\"></a>\r\n");
      out.write("                            <div class=\"info\">\r\n");
      out.write("                                <h3>IRONMAN</h3>\r\n");
      out.write("                                <P>TONY STARK</P>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"\"><img src=\"../img/characters10.png\"  alt=\"thor\"></a>\r\n");
      out.write("                            <div class=\"info\">\r\n");
      out.write("                                <h3>THOR</h3>\r\n");
      out.write("                                <P>GOD OF THUNDER</P>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"\"><img src=\"../img/characters11.png\"  alt=\"blackwidow\"></a>\r\n");
      out.write("                            <div class=\"info\">\r\n");
      out.write("                                <h3>BLACK WIDOW</h3>\r\n");
      out.write("                                <P>NATALIA ROMANOVA</P>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"\"><img src=\"../img/characters12.png\"   alt=\"starllord\"></a>                \r\n");
      out.write("                            <div class=\"info\">\r\n");
      out.write("                                <h3>STAR-LORD</h3>\r\n");
      out.write("                                <P>PETER QUILL</P>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>    \r\n");
      out.write("                </div>\r\n");
      out.write("            </section>\r\n");
      out.write("            <div class=\"page\">\r\n");
      out.write("                <a>&lt;&lt;</a>\r\n");
      out.write("                <a>&lt;</a>\r\n");
      out.write("                <a>1</a>\r\n");
      out.write("                <a>2</a>\r\n");
      out.write("                <a>3</a>\r\n");
      out.write("                <a>4</a>\r\n");
      out.write("                <a>&gt;</a>\r\n");
      out.write("                <a>&gt;&gt;</a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("        <!-- 업다운 버튼 -->\r\n");
      out.write("        <div class=\"fixed_btn\">\r\n");
      out.write("            <div class=\"box_updown\">\r\n");
      out.write("                <a class=\"btn_up\">UP</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"box_updown\">\r\n");
      out.write("                <a class=\"btn_down\">DOWN</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </main>\r\n");
      out.write("    <footer class=\"footer\">\r\n");
      out.write("        <div class=\"footer_area\">\r\n");
      out.write("            <div class=\"ft_level1\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <a href=\"../index.html\">\r\n");
      out.write("                        <img src=\"../img/Marvel_Logo.png\" alt=\"logo\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a>ABOUT MARVEL</a></li>\r\n");
      out.write("                        <li><a>HELP/FAQS</a></li>\r\n");
      out.write("                        <li><a>CAREERS</a></li>\r\n");
      out.write("                        <li><a>INTERNSHIP</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a>ADVERTISING</a></li>\r\n");
      out.write("                        <li><a>DISNEY</a></li>\r\n");
      out.write("                        <li><a>MARVELHQ.COM</a></li>\r\n");
      out.write("                        <li><a>REDEEM DIGITAL COMICS</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"ft_level2\">\r\n");
      out.write("                <nav>\r\n");
      out.write("                    <a>Terms of Use</a>\r\n");
      out.write("                    <a>Privacy Policy</a>\r\n");
      out.write("                    <a>Your California Privacy Rights</a>\r\n");
      out.write("                    <a>Do Not Sell My Personal Information</a>\r\n");
      out.write("                    <a>Children's Online Privacy Policy</a>\r\n");
      out.write("                    <a>License Agreement</a>\r\n");
      out.write("                    <a>Interest-Based Ads</a>\r\n");
      out.write("                    <a>Marvel Insider Terms</a>\r\n");
      out.write("                    <span>©2022 MARVEL</span>\r\n");
      out.write("                </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"../js/jquery-3.6.1.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/swiper/swiper-bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"../js/main.js\"></script>\r\n");
      out.write("    <script src=\"../js/common.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
